### ISSUE TITLE
Given example does not run

### ISSUE THREAD

**Issue by taochenshh** [stanford-iprl-lab/GRAC#2]
Hi,

Thanks for open-souring the code. I am trying to play around with the code. But it seems the GRAC class in grac.py misses some keyword arguments. And I couldn't run the given example. 
```
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    policy = GRAC.GRAC(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'no_critic_cem'
```

```
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    policy = GRAC.GRAC(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'policy_noise'
```

**Comment by yifan-you-37** [comment]
Hi Tao,

Thanks for letting us know! This issue was because some outdated options in main.py were still passed in to GRAC.py, which does not accept those options anymore. I've updated main.py so now this bug should be fixed!

Let me know if there's anything else I can help with.

Thanks,

Yifan

**Comment by taochenshh** [comment]
Thanks. It works now.
